import { FileText, Trash2, Upload } from 'lucide-react';
import { useState } from 'react';
import type { PdfDocument } from '../types';

interface Props { documents: PdfDocument[]; activeId?: string; onUpload(files: FileList | null): void; onSelect(id: string): void; onRemove?(id: string): void; }
export function DocumentRail({ documents, activeId, onUpload, onSelect, onRemove }: Props) {
  const [dragging, setDragging] = useState(false);
  const isPdf = (file: File) => file.type === 'application/pdf' || file.name.toLowerCase().endsWith('.pdf');
  return <aside className="document-rail"><div className="rail-head"><span className="wordmark">fieldly</span><span className="privacy">Local only</span></div><label className={`upload-button ${dragging ? 'dragging' : ''}`} onDragEnter={(event) => { event.preventDefault(); setDragging(true); }} onDragOver={(event) => { event.preventDefault(); event.dataTransfer.dropEffect = 'copy'; }} onDragLeave={(event) => { if (event.currentTarget === event.target) setDragging(false); }} onDrop={(event) => { event.preventDefault(); setDragging(false); const files = Array.from(event.dataTransfer.files).filter(isPdf); if (files.length) onUpload(files as unknown as FileList); }}><Upload size={17} /> {dragging ? 'Drop PDF here' : 'Upload PDF'}<input aria-label="Upload PDF" type="file" accept="application/pdf,.pdf" multiple onChange={(event) => onUpload(event.target.files)} /></label><p className="rail-label">Documents</p><div className="document-list">{documents.length === 0 ? <p className="empty-list">PDFs you add will stay on this device.</p> : documents.map((document) => <div className={`document-row ${activeId === document.id ? 'selected' : ''}`} key={document.id}><button type="button" className="document-select" onClick={() => onSelect(document.id)}><FileText size={17} /><span><strong title={document.filename}>{document.filename}</strong><small>{document.pageCount} {document.pageCount === 1 ? 'page' : 'pages'} · {document.fields.length} fields</small></span></button><button className="document-remove" aria-label={`Remove ${document.filename}`} type="button" onClick={(event) => { event.stopPropagation(); onRemove?.(document.id); }}><Trash2 size={15} /></button></div>)}</div></aside>;
}
