import { ChevronLeft, ChevronRight, ScanLine, X, ZoomIn, ZoomOut } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import * as pdfjsLib from 'pdfjs-dist';
import type { ExtractedField, NormalizedRect, PdfDocument } from '../types';
import { normalizeRect } from '../lib/geometry';
import { extractTextFromRegion } from '../lib/pdfExtraction';
import { getPdfLoadOptions } from '../lib/pdfLoader';

pdfjsLib.GlobalWorkerOptions.workerSrc = new URL('pdfjs-dist/build/pdf.worker.min.mjs', import.meta.url).toString();
type CropSession = { fieldId: string; cropId: string };
interface Props { document: PdfDocument; fields: ExtractedField[]; drawingName?: string; selectedFieldId?: string; onBeginCrop(rect: NormalizedRect, page: number): CropSession | undefined; onFinishCrop(session: CropSession, value: string, error?: string): void; onDeleteCrop(fieldId: string, cropId: string): void; }
export function PdfCanvas({ document, fields, drawingName, selectedFieldId, onBeginCrop, onFinishCrop, onDeleteCrop }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const overlayRef = useRef<HTMLDivElement>(null); const [pageNumber, setPageNumber] = useState(1); const [zoom, setZoom] = useState(1.2); const [page, setPage] = useState<any>(); const [viewport, setViewport] = useState<any>(); const [start, setStart] = useState<{ x: number; y: number } | null>(null); const [draft, setDraft] = useState<NormalizedRect | null>(null);
  useEffect(() => setPageNumber(1), [document.id]);
  useEffect(() => { let cancelled = false; (async () => { const pdf = await pdfjsLib.getDocument(getPdfLoadOptions(document.data.slice(0))).promise; const nextPage = await pdf.getPage(pageNumber); const nextViewport = nextPage.getViewport({ scale: zoom }); const canvas = canvasRef.current; if (cancelled || !canvas) return; canvas.width = Math.ceil(nextViewport.width); canvas.height = Math.ceil(nextViewport.height); await nextPage.render({ canvas, canvasContext: canvas.getContext('2d')!, viewport: nextViewport }).promise; if (!cancelled) { setPage(nextPage); setViewport(nextViewport); } })().catch(console.error); return () => { cancelled = true; }; }, [document, pageNumber, zoom]);
  const point = (event: React.PointerEvent) => { const box = overlayRef.current!.getBoundingClientRect(); return { x: Math.max(0, Math.min(box.width, event.clientX - box.left)), y: Math.max(0, Math.min(box.height, event.clientY - box.top)) }; };
  const move = (event: React.PointerEvent) => { if (!start || !overlayRef.current) return; const end = point(event); setDraft(normalizeRect({ x: Math.min(start.x, end.x), y: Math.min(start.y, end.y), width: Math.abs(end.x - start.x), height: Math.abs(end.y - start.y) }, overlayRef.current.clientWidth, overlayRef.current.clientHeight)); };
  const finish = async () => { if (!start || !draft || !drawingName || !page || !viewport) { setStart(null); return; } const session = onBeginCrop(draft, pageNumber); setStart(null); setDraft(null); if (!session) return; try { onFinishCrop(session, await extractTextFromRegion(page, draft, viewport)); } catch { onFinishCrop(session, '', 'Could not read this crop. Try a clearer area.'); } };
  const visibleCrops = fields.flatMap((field) => field.crops.filter((crop) => crop.page === pageNumber).map((crop) => ({ field, crop }))); const rectStyle = (rect: NormalizedRect) => ({ left: `${rect.x * 100}%`, top: `${rect.y * 100}%`, width: `${rect.width * 100}%`, height: `${rect.height * 100}%` });
  return <section className="canvas-pane"><header className="canvas-toolbar"><div><button aria-label="Previous page" type="button" disabled={pageNumber === 1} onClick={() => setPageNumber((n) => n - 1)}><ChevronLeft size={18} /></button><span>Page {pageNumber} of {document.pageCount}</span><button aria-label="Next page" type="button" disabled={pageNumber === document.pageCount} onClick={() => setPageNumber((n) => n + 1)}><ChevronRight size={18} /></button></div><div><button aria-label="Zoom out" type="button" onClick={() => setZoom((z) => Math.max(.7, z - .15))}><ZoomOut size={18} /></button><span>{Math.round(zoom * 100)}%</span><button aria-label="Zoom in" type="button" onClick={() => setZoom((z) => Math.min(2.2, z + .15))}><ZoomIn size={18} /></button></div></header><div className="paper-scroll"><div className={`paper ${drawingName ? 'drawing' : ''}`}><canvas ref={canvasRef} /><div ref={overlayRef} data-testid="pdf-overlay" className="pdf-overlay" onPointerDown={(event) => drawingName && (event.currentTarget.setPointerCapture(event.pointerId), setStart(point(event)), setDraft(null))} onPointerMove={move} onPointerUp={finish}>{visibleCrops.map(({ field, crop }) => <div className={`crop-box ${field.id === selectedFieldId ? 'selected' : ''}`} style={rectStyle(crop.rect)} key={crop.id}><span>{field.name}</span><button className="crop-cancel" aria-label={`Remove crop for ${field.name}`} type="button" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); onDeleteCrop(field.id, crop.id); }}><X size={14} /></button></div>)}{draft && <div className="crop-box draft" style={rectStyle(draft)}><span>{drawingName}</span></div>}</div></div></div>{drawingName && <div className="draw-hint"><ScanLine size={16} /> Drag to add a crop area for “{drawingName}”</div>}</section>;
}
