import { useCallback, useState } from 'react';
import * as pdfjsLib from 'pdfjs-dist';
import { DocumentRail } from './components/DocumentRail';
import { FieldsPanel } from './components/FieldsPanel';
import { PdfCanvas } from './components/PdfCanvas';
import { downloadText, formatExportText } from './lib/exportText';
import { getPdfLoadOptions } from './lib/pdfLoader';
import type { CropArea, ExtractedField, NormalizedRect, PdfDocument } from './types';

pdfjsLib.GlobalWorkerOptions.workerSrc = new URL('pdfjs-dist/build/pdf.worker.min.mjs', import.meta.url).toString();
const updateDocument = (docs: PdfDocument[], id: string, updater: (doc: PdfDocument) => PdfDocument) => docs.map((doc) => doc.id === id ? updater(doc) : doc);
const DEFAULT_FIELD_NAMES = ['Shipper', 'Consignee', 'Notify Party', 'Description of Goods', 'Shipping Marks', 'Total', 'Weight'];
export const createDefaultFields = (): ExtractedField[] => DEFAULT_FIELD_NAMES.map((name) => ({ id: crypto.randomUUID(), name, page: 1, crops: [], value: '', status: 'idle' }));

export default function App() {
  const [documents, setDocuments] = useState<PdfDocument[]>([]); const [activeId, setActiveId] = useState<string>(); const [selectedFieldId, setSelectedFieldId] = useState<string>(); const [error, setError] = useState(''); const [detailsExpanded, setDetailsExpanded] = useState(false);
  const active = documents.find((doc) => doc.id === activeId); const selected = active?.fields.find((field) => field.id === selectedFieldId);
  const onUpload = useCallback(async (files: FileList | null) => { if (!files) return; const added: PdfDocument[] = []; for (const file of Array.from(files)) { try { const data = await file.arrayBuffer(); const pdf = await pdfjsLib.getDocument(getPdfLoadOptions(data.slice(0))).promise; added.push({ id: crypto.randomUUID(), filename: file.name, data, pageCount: pdf.numPages, fields: createDefaultFields() }); } catch { setError(`Could not open ${file.name}.`); } } if (added.length) { setDocuments((current) => [...current, ...added]); setActiveId((current) => current ?? added[0].id); } }, []);
  const changeField = (id: string, patch: Partial<ExtractedField>) => activeId && setDocuments((current) => updateDocument(current, activeId, (doc) => ({ ...doc, fields: doc.fields.map((field) => field.id === id ? { ...field, ...patch } : field) })));
  const createField = (name: string) => { if (!activeId) return; const field: ExtractedField = { id: crypto.randomUUID(), name, page: 1, crops: [], value: '', status: 'idle' }; setDocuments((current) => updateDocument(current, activeId, (doc) => ({ ...doc, fields: [...doc.fields, field] }))); setSelectedFieldId(field.id); };
  const beginCrop = (rect: NormalizedRect, page: number) => { if (!selected) return; const crop: CropArea = { id: crypto.randomUUID(), page, rect, value: '' }; const crops = [...selected.crops, crop]; changeField(selected.id, { page, rect, crops, status: 'extracting', error: undefined }); return { fieldId: selected.id, cropId: crop.id }; };
  const finishCrop = ({ fieldId, cropId }: { fieldId: string; cropId: string }, value: string, error?: string) => { if (!activeId) return; setDocuments((current) => updateDocument(current, activeId, (doc) => ({ ...doc, fields: doc.fields.map((field) => { if (field.id !== fieldId) return field; const crops = field.crops.map((crop) => crop.id === cropId ? { ...crop, value } : crop); return { ...field, crops, value: crops.map((crop) => crop.value).filter(Boolean).join('\n'), status: error ? 'error' : 'ready', error }; }) }))); };
  const deleteCrop = (fieldId: string, cropId: string) => { if (!activeId) return; setDocuments((current) => updateDocument(current, activeId, (doc) => ({ ...doc, fields: doc.fields.map((field) => { if (field.id !== fieldId) return field; const crops = field.crops.filter((crop) => crop.id !== cropId); return { ...field, crops, value: crops.map((crop) => crop.value).filter(Boolean).join('\n'), status: crops.length ? 'ready' : 'idle', error: undefined }; }) }))); };
  const removeDocument = (id: string) => setDocuments((current) => { const remaining = current.filter((doc) => doc.id !== id); if (activeId === id) { setActiveId(remaining[0]?.id); setSelectedFieldId(undefined); } return remaining; });
  const exportSiForm = async () => { const fields = Object.fromEntries((active?.fields ?? []).map((field) => [field.name, field.value])); console.log(fields); if (!window.location.pathname.startsWith('/document-ocr/')) return; const hostWindow = (window.parent === window ? window : window.parent) as Window & typeof globalThis & { ShowSpinner?: () => void; HideSpinner?: () => void }; hostWindow.ShowSpinner?.(); try { const response = await fetch('/DocumentOCR/Generate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fields }) }); if (!response.ok) throw new Error('Report generation failed.'); const filename = response.headers.get('content-disposition')?.match(/filename="?([^";]+)"?/)?.[1] ?? 'ShippingInstructionOCR.xlsx'; const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); } catch { setError('Could not generate the Shipping Instruction report.'); } finally { hostWindow.HideSpinner?.(); } };
  return <div className={`app-shell ${detailsExpanded ? 'details-expanded' : ''}`}><DocumentRail documents={documents} activeId={activeId} onUpload={onUpload} onSelect={(id) => { setActiveId(id); setSelectedFieldId(undefined); }} onRemove={removeDocument} /><main className="workspace">{error && <p className="error-banner">{error}</p>}{active ? <PdfCanvas document={active} fields={active.fields} drawingName={selected?.name} selectedFieldId={selectedFieldId} onBeginCrop={beginCrop} onFinishCrop={finishCrop} onDeleteCrop={deleteCrop} /> : <section className="welcome"><p className="eyebrow">Private document workspace</p><h1>PDF Field Extractor</h1><p>Upload PDFs, name the details you need, then draw a precise capture area. Your files never leave this browser.</p></section>}</main><FieldsPanel fields={active?.fields ?? []} drawing={Boolean(selectedFieldId)} selectedFieldId={selectedFieldId} expanded={detailsExpanded} onExpandedChange={setDetailsExpanded} onCreateField={createField} onSelectField={setSelectedFieldId} onFieldChange={changeField} onDelete={(id) => activeId && setDocuments((current) => updateDocument(current, activeId, (doc) => ({ ...doc, fields: doc.fields.filter((field) => field.id !== id) })))} onExport={exportSiForm} /></div>;
}
